import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { TooltipProvider } from '@/components/ui/tooltip';
import { SITE_URL } from '@/lib/site-url';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const SITE_DESCRIPTION =
  'Generate AutoHotkey (Windows) or Karabiner-Elements (macOS) configs in your browser. Standardise keyboard shortcuts across every desktop app — share configs via URL, import existing ones, simulate before installing.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'HotkeySync — Standardise hotkeys across desktop apps',
    template: '%s — HotkeySync',
  },
  description: SITE_DESCRIPTION,
  applicationName: 'HotkeySync',
  keywords: [
    'hotkeys',
    'keyboard shortcuts',
    'AutoHotkey',
    'Karabiner',
    'AHK',
    'remap',
    'Windows',
    'macOS',
    'productivity',
  ],
  authors: [{ name: 'HotkeySync' }],
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: 'HotkeySync',
    title: 'HotkeySync — Standardise hotkeys across desktop apps',
    description: SITE_DESCRIPTION,
    locale: 'en_US',
    // OG image is generated by src/app/opengraph-image.tsx and auto-attached.
  },
  twitter: {
    card: 'summary_large_image',
    title: 'HotkeySync — Standardise hotkeys across desktop apps',
    description: SITE_DESCRIPTION,
    // Twitter image is auto-derived from the OG image.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
  },
  icons: { icon: '/favicon.ico' },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider delayDuration={300}>{children}</TooltipProvider>
      </body>
    </html>
  );
}
