import {
  AHK_KEY_MAP,
  AHK_MODIFIER_MAP,
  comboToAHK,
  parseKeyCombo,
  type KeyCombo,
  type TriggerKey,
} from '@/lib/keys';
import type { Config } from '@/types';
import { getAppById, groupRulesByAppId } from '@/lib/generators/shared';

const AHK_SEND_KEY_MAP: Partial<Record<TriggerKey, string>> = {
  tab: '{Tab}',
  escape: '{Escape}',
  return_or_enter: '{Enter}',
  delete_or_backspace: '{Backspace}',
  delete_forward: '{Delete}',
  up_arrow: '{Up}',
  down_arrow: '{Down}',
  left_arrow: '{Left}',
  right_arrow: '{Right}',
  home: '{Home}',
  end: '{End}',
  page_up: '{PgUp}',
  page_down: '{PgDn}',
  space: '{Space}',
  f1: '{F1}', f2: '{F2}', f3: '{F3}', f4: '{F4}',
  f5: '{F5}', f6: '{F6}', f7: '{F7}', f8: '{F8}',
  f9: '{F9}', f10: '{F10}', f11: '{F11}', f12: '{F12}',
};

function comboToAHKSend(combo: KeyCombo): string {
  const prefix = combo.modifiers.map((m) => AHK_MODIFIER_MAP[m]).join('');
  const braced = AHK_SEND_KEY_MAP[combo.key];
  const keyPart = braced ?? AHK_KEY_MAP[combo.key];
  return `${prefix}${keyPart}`;
}

function isoDateOnly(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Polling-based tap-vs-hold helper injected once per file when any tap_hold
 * rule exists. AHK has no native to_if_alone — this emulates it.
 *
 * Caveat baked into the comment for the eventual user: this can mis-fire on
 * fast typing rolls. The Karabiner side uses a native primitive and doesn't
 * have this caveat. The UI surfaces this disclosure too.
 *
 * Generated as a string constant so the Vitest tests can assert verbatim.
 */
export const AHK_TAP_HOLD_HELPER = [
  '; HotkeySync tap-hold helper. Polls trigger key every 10ms during the timeout',
  '; window. Note: AHK has no native tap-vs-hold; fast typing rolls may mis-fire.',
  '; For high-frequency keys, prefer a basic remap.',
  'TapHoldAction(timeoutMs, tapAction, holdAction) {',
  '  pureKey := RegExReplace(A_ThisHotkey, "^[\\^!+#<>*~$]+", "")',
  '  endTime := A_TickCount + timeoutMs',
  '  while (A_TickCount < endTime) {',
  '    if !GetKeyState(pureKey, "P") {',
  '      SendInput(tapAction)',
  '      return',
  '    }',
  '    Sleep(10)',
  '  }',
  '  SendInput(holdAction)',
  '  KeyWait(pureKey)',
  '}',
  '',
].join('\n');

export function generateAHK(config: Config): string {
  const grouped = groupRulesByAppId(config.rules);
  const uniqueAppCount = grouped.size;
  const header = [
    '; Generated by HotkeySync — https://hotkeysync.app',
    '; OS: Windows | AutoHotkey v2',
    `; Rules: ${config.rules.length} across ${uniqueAppCount} apps`,
    `; Generated: ${isoDateOnly()}`,
    ';',
    '#Requires AutoHotkey v2.0+',
    '#SingleInstance Force',
    '',
  ];

  if (config.rules.length === 0) {
    return [...header, '; No rules configured. Add rules in HotkeySync and regenerate.', ''].join('\n');
  }

  // Inject the tap-hold helper only when needed. Keeps output identical to
  // pre-T2.3 for users who only use basic rules.
  const hasTapHold = config.rules.some((r) => r.kind === 'tap_hold');
  const prologue: string[] = hasTapHold ? [AHK_TAP_HOLD_HELPER] : [];

  const blocks: string[] = [];
  for (const [appId, appRules] of grouped) {
    const app = getAppById(appId);
    if (!app) {
      // Defensive: store prevents unknown appIds; surface a comment if one slips through.
      blocks.push(`; Note: skipped rule for unknown app '${appId}'`);
      blocks.push('');
      continue;
    }
    blocks.push(`; ═══ ${app.name} ═══`);
    blocks.push(`#HotIf WinActive("ahk_exe ${app.exeName}")`);
    for (const rule of appRules) {
      if (rule.kind === 'disable') {
        let triggerStr: string;
        try {
          triggerStr = comboToAHK(parseKeyCombo(rule.trigger));
        } catch {
          blocks.push(
            `; Skipped malformed disable rule (trigger="${rule.trigger}")`,
          );
          continue;
        }
        // `return` exits the hotkey handler before the OS sees the keystroke,
        // effectively swallowing it. AHK community canonical pattern.
        blocks.push(`${triggerStr}:: return  ; ${rule.description} (disabled)`);
        continue;
      }
      if (rule.kind === 'tap_hold') {
        let triggerStr: string;
        let tapStr: string;
        let holdStr: string;
        try {
          triggerStr = comboToAHK(parseKeyCombo(rule.trigger));
          tapStr = comboToAHKSend(parseKeyCombo(rule.tapAction));
          holdStr = comboToAHKSend(parseKeyCombo(rule.holdAction));
        } catch {
          blocks.push(
            `; Skipped malformed tap_hold rule (trigger="${rule.trigger}", tap="${rule.tapAction}", hold="${rule.holdAction}")`,
          );
          continue;
        }
        blocks.push(
          `${triggerStr}:: TapHoldAction(${rule.tapTimeoutMs}, "${tapStr}", "${holdStr}")  ; ${rule.description}`,
        );
        continue;
      }
      let triggerStr: string;
      let actionStr: string;
      try {
        triggerStr = comboToAHK(parseKeyCombo(rule.trigger));
        actionStr = comboToAHKSend(parseKeyCombo(rule.action));
      } catch {
        blocks.push(`; Skipped malformed rule (trigger="${rule.trigger}", action="${rule.action}")`);
        continue;
      }
      blocks.push(`${triggerStr}:: Send("${actionStr}")  ; ${rule.description}`);
    }
    blocks.push('#HotIf');
    blocks.push('');
  }

  return [...header, ...prologue, ...blocks].join('\n');
}
