/**
 * AHK → HotkeySync rule importer.
 *
 * Goals:
 *   1. Perfect round-trip for AHK files generated by HotkeySync itself.
 *   2. Best-effort import for hand-written AHK v2 files that follow the
 *      common pattern (`#HotIf WinActive("ahk_exe X.exe")` blocks with
 *      `<trigger>:: Send("<action>")` lines).
 *
 * Out of scope (yet):
 *   - Send() with multi-key macros (`Send("hello{Tab}world")`)
 *   - Hotstrings (`::btw::by the way`)
 *   - Conditional logic, function calls, variables
 *   - AHK v1 syntax
 *
 * Anything we can't parse cleanly is added to `warnings` so the user can
 * triage instead of silently losing rules.
 */

import appsData from '@/data/apps.json';
import type { App, HotkeyRule, OS } from '@/types';
import {
  TAP_HOLD_DEFAULT_TIMEOUT_MS,
  TAP_HOLD_MIN_TIMEOUT_MS,
  TAP_HOLD_MAX_TIMEOUT_MS,
  GLOBAL_APP_ID,
} from '@/types';
import {
  serializeKeyCombo,
  type Modifier,
  type TriggerKey,
} from '@/lib/keys';

const APPS = appsData as App[];

// Lowercased exeName → appId. Real-world AHK paths may differ in case
// (chrome.exe vs Chrome.EXE), so we compare case-insensitively. macOS-only
// apps without an exeName are simply absent from the lookup (their AHK
// directives, if any, will be reported as unknown-app warnings on import).
const EXE_LOOKUP = new Map<string, string>(
  APPS.filter((a): a is App & { exeName: string } => Boolean(a.exeName)).map(
    (a) => [a.exeName.toLowerCase(), a.id],
  ),
);

// AHK modifier symbols → our Modifier names.
const AHK_MODIFIER_REVERSE: Record<string, Modifier> = {
  '^': 'ctrl',
  '+': 'shift',
  '!': 'alt',
  '#': 'meta',
};

// Named special keys (case-insensitive). Both braced and unbraced forms.
const NAMED_KEY_REVERSE: Record<string, TriggerKey> = {
  tab: 'tab',
  escape: 'escape',
  esc: 'escape',
  enter: 'return_or_enter',
  return: 'return_or_enter',
  space: 'space',
  backspace: 'delete_or_backspace',
  bs: 'delete_or_backspace',
  delete: 'delete_forward',
  del: 'delete_forward',
  up: 'up_arrow',
  down: 'down_arrow',
  left: 'left_arrow',
  right: 'right_arrow',
  home: 'home',
  end: 'end',
  pgup: 'page_up',
  pgdn: 'page_down',
  f1: 'f1', f2: 'f2', f3: 'f3', f4: 'f4',
  f5: 'f5', f6: 'f6', f7: 'f7', f8: 'f8',
  f9: 'f9', f10: 'f10', f11: 'f11', f12: 'f12',
  capslock: 'caps_lock',
  caps_lock: 'caps_lock',
};

// Single-char symbol → TriggerKey.
const SYMBOL_REVERSE: Record<string, TriggerKey> = {
  ',': 'comma',
  '.': 'period',
  '/': 'slash',
  ';': 'semicolon',
  "'": 'quote',
  '[': 'open_bracket',
  ']': 'close_bracket',
  '\\': 'backslash',
  '`': 'grave_accent',
  '-': 'minus',
  '=': 'equal',
};

function parseSingleKey(raw: string): TriggerKey | null {
  if (raw.length === 0) return null;

  // Braced named key: {Tab}, {F1}, {PgUp}
  if (raw.startsWith('{') && raw.endsWith('}') && raw.length > 2) {
    const inner = raw.slice(1, -1).toLowerCase();
    return NAMED_KEY_REVERSE[inner] ?? null;
  }

  const lower = raw.toLowerCase();
  // Named (unbraced) — Tab, F1, Escape
  if (NAMED_KEY_REVERSE[lower] !== undefined) {
    return NAMED_KEY_REVERSE[lower];
  }

  // Single letter / digit
  if (raw.length === 1) {
    const c = lower;
    if (/^[a-z0-9]$/.test(c)) return c as TriggerKey;
    if (SYMBOL_REVERSE[c] !== undefined) return SYMBOL_REVERSE[c];
  }
  return null;
}

interface ParsedCombo {
  combo: string;
  warning?: string;
}

/** Parse an AHK key expression (e.g. `^+{Tab}` or `^p` or `Tab`) into a
 *  canonical serialised KeyCombo. Returns null with a reason if unparseable.
 */
function parseAHKKeyExpression(expr: string): ParsedCombo | null {
  if (expr.length === 0) return null;

  const mods: Modifier[] = [];
  let i = 0;
  while (i < expr.length && AHK_MODIFIER_REVERSE[expr[i]]) {
    mods.push(AHK_MODIFIER_REVERSE[expr[i]]);
    i++;
  }

  const remainder = expr.slice(i);
  const key = parseSingleKey(remainder);
  if (key === null) return null;

  return {
    combo: serializeKeyCombo({
      modifiers: Array.from(new Set(mods)).sort((a, b) => a.localeCompare(b)),
      key,
    }),
  };
}

export interface AHKImportWarning {
  line: number;
  text: string;
  reason: string;
}

export interface AHKImportResult {
  rules: HotkeyRule[];
  warnings: AHKImportWarning[];
  unknownAppExes: string[];
  /**
   * Suggested `selectedAppIds` to seed the picker — every app referenced by
   * a successfully imported rule, in first-encounter order.
   */
  selectedAppIds: string[];
  /** Always 'windows' for AHK imports. */
  os: OS;
}

const HOTIF_RX = /^#HotIf\s+WinActive\(["']ahk_exe\s+([^"')]+)["']\)/i;
const HOTIF_BARE_RX = /^#HotIf\s*$/i;
/**
 * Matches a HotkeySync-emitted global-with-exceptions directive, e.g.
 *   `#HotIf !(WinActive("ahk_exe a.exe") || WinActive("ahk_exe b.exe"))`
 * Captures the inner string; we then split it on `||` and pull exe names.
 */
const HOTIF_GLOBAL_NOT_RX = /^#HotIf\s+!\(\s*(WinActive\([^)]*\)(?:\s*\|\|\s*WinActive\([^)]*\))*)\s*\)/i;
const WIN_ACTIVE_EXE_RX = /WinActive\(["']ahk_exe\s+([^"')]+)["']\)/gi;
// Lowercased exeName → appId lookup is initialised below; we capture it here
// so HOTIF_GLOBAL_NOT_RX parsing can resolve excluded exes to app ids.
const RULE_RX =
  /^(\S+?)::\s*Send\(\s*["']([^"']*)["']\s*\)\s*(?:;(.*))?$/;
/**
 * Matches a HotkeySync-emitted disable rule:
 *   `^q:: return  ; Stop Firefox quitting (disabled)`
 * AHK has many ways to no-op a key; we only round-trip the canonical
 * `Trigger:: return` form that our generator emits.
 */
const DISABLE_RULE_RX = /^(\S+?)::\s*return\s*(?:;(.*))?$/i;
/**
 * Matches the tap-hold call generated by ahk.ts:
 *   `^p:: TapHoldAction(200, "^,", "^+w")  ; description`
 * Capture groups: 1=trigger, 2=ms, 3=tap-action, 4=hold-action, 5=description.
 */
const TAP_HOLD_RULE_RX =
  /^(\S+?)::\s*TapHoldAction\(\s*(\d+)\s*,\s*["']([^"']+)["']\s*,\s*["']([^"']+)["']\s*\)\s*(?:;(.*))?$/;

export function parseAHK(source: string): AHKImportResult {
  const rules: HotkeyRule[] = [];
  const warnings: AHKImportWarning[] = [];
  const unknownAppExes: string[] = [];
  const selectedOrder: string[] = [];
  const seenApps = new Set<string>();

  // Scope tracking. Three states:
  //   - currentAppId = string  → we're inside `#HotIf WinActive(known_exe)`
  //                              OR inside `#HotIf !(...)` (then appId === __global)
  //                              OR we've never seen any #HotIf (implicit global)
  //   - currentAppId = null    → we just hit an unknown-exe #HotIf; subsequent
  //                              rules until the next #HotIf reset/known are
  //                              warned-and-skipped (preserves user intent)
  //   - currentExceptApps set  → only when inside `#HotIf !(WinActive ...)`,
  //                              the exclusion list to attach to each rule
  let currentAppId: string | null = GLOBAL_APP_ID;
  let currentExceptApps: string[] | null = null;
  const lines = source.split(/\r?\n/);

  for (let idx = 0; idx < lines.length; idx++) {
    const raw = lines[idx];
    const line = raw.trim();
    if (line.length === 0) continue;
    if (line.startsWith(';')) continue;

    // #HotIf WinActive(...)
    const hotIfMatch = line.match(HOTIF_RX);
    if (hotIfMatch) {
      const exe = hotIfMatch[1].trim();
      const appId = EXE_LOOKUP.get(exe.toLowerCase());
      if (!appId) {
        if (!unknownAppExes.includes(exe)) unknownAppExes.push(exe);
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: `Unknown exeName "${exe}" — not in app catalog. Rules inside this block will be skipped.`,
        });
        currentAppId = null;
        currentExceptApps = null;
        continue;
      }
      currentAppId = appId;
      currentExceptApps = null;
      if (!seenApps.has(appId)) {
        seenApps.add(appId);
        selectedOrder.push(appId);
      }
      continue;
    }

    // #HotIf !(WinActive("ahk_exe a.exe") || WinActive(...)) — global-with-exceptions
    const hotIfGlobalNot = line.match(HOTIF_GLOBAL_NOT_RX);
    if (hotIfGlobalNot) {
      const inner = hotIfGlobalNot[1];
      const exes: string[] = [];
      const unknownExceptions: string[] = [];
      let match: RegExpExecArray | null;
      const rx = new RegExp(WIN_ACTIVE_EXE_RX.source, 'gi');
      while ((match = rx.exec(inner)) !== null) {
        const exe = match[1].trim();
        const id = EXE_LOOKUP.get(exe.toLowerCase());
        if (id) exes.push(id);
        else unknownExceptions.push(exe);
      }
      currentAppId = GLOBAL_APP_ID;
      currentExceptApps = exes.length > 0 ? exes : null;
      if (!seenApps.has(GLOBAL_APP_ID)) {
        seenApps.add(GLOBAL_APP_ID);
        selectedOrder.push(GLOBAL_APP_ID);
      }
      if (unknownExceptions.length > 0) {
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: `Global rule excludes ${unknownExceptions.length} unknown exe(s) — those exclusions were dropped: ${unknownExceptions.slice(0, 3).join(', ')}${unknownExceptions.length > 3 ? '…' : ''}`,
        });
      }
      continue;
    }

    if (HOTIF_BARE_RX.test(line)) {
      // Resetting #HotIf means "back to global scope".
      currentAppId = GLOBAL_APP_ID;
      currentExceptApps = null;
      continue;
    }

    // Skip directives (#Requires, #SingleInstance, #Include, …), but NOT rule
    // lines whose trigger uses the `#` (meta/Win) modifier — those contain `::`.
    if (line.startsWith('#') && !line.includes('::')) continue;

    // Try disable pattern (`Trigger:: return`) before basic — both contain `::`.
    const disableMatch = line.match(DISABLE_RULE_RX);
    if (disableMatch) {
      const [, disTriggerExpr, disDescriptionRaw] = disableMatch;
      const disDescription = (disDescriptionRaw ?? '')
        .trim()
        // Strip the "(disabled)" suffix our generator appends so re-edits read cleanly.
        .replace(/\s*\(disabled\)\s*$/i, '')
        .trim();
      const disTrigger = parseAHKKeyExpression(disTriggerExpr);
      if (!disTrigger) {
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: `Could not parse disable rule trigger "${disTriggerExpr}".`,
        });
        continue;
      }
      if (currentAppId === null) {
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: 'disable rule inside an unresolved-app #HotIf block — skipped.',
        });
        continue;
      }
      const disAppId = currentAppId;
      if (!seenApps.has(disAppId)) {
        seenApps.add(disAppId);
        selectedOrder.push(disAppId);
      }
      rules.push({
        kind: 'disable',
        appId: disAppId,
        trigger: disTrigger.combo,
        description: disDescription.length > 0 ? disDescription : 'Imported from AHK (disabled)',
        ...(currentExceptApps ? { exceptApps: currentExceptApps } : {}),
      });
      continue;
    }

    // Try tap_hold pattern FIRST (its `::` token also matches the basic regex,
    // so order matters).
    const tapHoldMatch = line.match(TAP_HOLD_RULE_RX);
    if (tapHoldMatch) {
      const [, thTriggerExpr, msStr, thTapExpr, thHoldExpr, thDescriptionRaw] =
        tapHoldMatch;
      const thDescription = (thDescriptionRaw ?? '').trim();
      const thTrigger = parseAHKKeyExpression(thTriggerExpr);
      const thTap = parseAHKKeyExpression(thTapExpr);
      const thHold = parseAHKKeyExpression(thHoldExpr);
      if (!thTrigger || !thTap || !thHold) {
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: `Could not parse tap_hold rule "${line}".`,
        });
        continue;
      }
      let timeoutMs = Number.parseInt(msStr, 10);
      if (!Number.isFinite(timeoutMs)) timeoutMs = TAP_HOLD_DEFAULT_TIMEOUT_MS;
      const clamped = Math.max(
        TAP_HOLD_MIN_TIMEOUT_MS,
        Math.min(TAP_HOLD_MAX_TIMEOUT_MS, timeoutMs),
      );
      if (clamped !== timeoutMs) {
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: `tap timeout ${timeoutMs}ms clamped to ${clamped}ms (allowed range ${TAP_HOLD_MIN_TIMEOUT_MS}–${TAP_HOLD_MAX_TIMEOUT_MS}ms).`,
        });
      }
      if (currentAppId === null) {
        warnings.push({
          line: idx + 1,
          text: raw,
          reason: 'tap_hold rule inside an unresolved-app #HotIf block — skipped.',
        });
        continue;
      }
      const thAppId = currentAppId;
      if (!seenApps.has(thAppId)) {
        seenApps.add(thAppId);
        selectedOrder.push(thAppId);
      }
      rules.push({
        kind: 'tap_hold',
        appId: thAppId,
        trigger: thTrigger.combo,
        tapAction: thTap.combo,
        holdAction: thHold.combo,
        tapTimeoutMs: clamped,
        description: thDescription.length > 0 ? thDescription : 'Imported from AHK',
        ...(currentExceptApps ? { exceptApps: currentExceptApps } : {}),
      });
      continue;
    }

    // Rule line
    const ruleMatch = line.match(RULE_RX);
    if (!ruleMatch) continue;
    const [, triggerExpr, actionExpr, descriptionRaw] = ruleMatch;
    const description = (descriptionRaw ?? '').trim();

    const triggerCombo = parseAHKKeyExpression(triggerExpr);
    if (!triggerCombo) {
      warnings.push({
        line: idx + 1,
        text: raw,
        reason: `Could not parse trigger expression "${triggerExpr}".`,
      });
      continue;
    }

    const actionCombo = parseAHKKeyExpression(actionExpr);
    if (!actionCombo) {
      warnings.push({
        line: idx + 1,
        text: raw,
        reason: `Could not parse action expression "${actionExpr}" (multi-key macros not supported yet).`,
      });
      continue;
    }

    if (currentAppId === null) {
      warnings.push({
        line: idx + 1,
        text: raw,
        reason: 'Rule inside an unresolved-app #HotIf block — skipped.',
      });
      continue;
    }
    const basicAppId = currentAppId;
    if (!seenApps.has(basicAppId)) {
      seenApps.add(basicAppId);
      selectedOrder.push(basicAppId);
    }
    rules.push({
      kind: 'basic',
      appId: basicAppId,
      trigger: triggerCombo.combo,
      action: actionCombo.combo,
      description: description.length > 0 ? description : 'Imported from AHK',
      ...(currentExceptApps ? { exceptApps: currentExceptApps } : {}),
    });
  }

  return {
    rules,
    warnings,
    unknownAppExes,
    selectedAppIds: selectedOrder,
    os: 'windows',
  };
}
